set(INCS 
  "Core/Inc"
  "Drivers/STM32F3xx_HAL_Driver/Inc"
  "Drivers/STM32F3xx_HAL_Driver/Inc/Legacy"
  "Drivers/CMSIS/Device/ST/STM32F3xx/Include"
  "Drivers/CMSIS/Include"
)

set(SRCS 
  "Core/Src/main.c"
  "Core/Src/stm32f3xx_it.c" 
  "Core/Src/stm32f3xx_hal_msp.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_tim.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_tim_ex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_uart.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_uart_ex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_rcc_ex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_gpio.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_dma.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_cortex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_pwr_ex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_flash.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_flash_ex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_i2c_ex.c" 
  "Drivers/STM32F3xx_HAL_Driver/Src/stm32f3xx_hal_exti.c" 
  "Core/Src/system_stm32f3xx.c" 

  "startup_stm32f303xe.s"
)